# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/v1/user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user/v1/user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1auser/v1/user_service.proto\x12\x07user.v1\"C\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"0\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"1\n\x12\x43reateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\".\n\x0fGetUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User2\x92\x01\n\x0bUserService\x12\x45\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\x12<\n\x07GetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponseB-Z+github.com/myshop/api/gen/go/user/v1;userv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/myshop/api/gen/go/user/v1;userv1'
  _globals['_USER']._serialized_start=39
  _globals['_USER']._serialized_end=106
  _globals['_CREATEUSERREQUEST']._serialized_start=108
  _globals['_CREATEUSERREQUEST']._serialized_end=156
  _globals['_CREATEUSERRESPONSE']._serialized_start=158
  _globals['_CREATEUSERRESPONSE']._serialized_end=207
  _globals['_GETUSERREQUEST']._serialized_start=209
  _globals['_GETUSERREQUEST']._serialized_end=242
  _globals['_GETUSERRESPONSE']._serialized_start=244
  _globals['_GETUSERRESPONSE']._serialized_end=290
  _globals['_USERSERVICE']._serialized_start=293
  _globals['_USERSERVICE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
