# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog/v1/catalog_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalog/v1/catalog_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n catalog/v1/catalog_service.proto\x12\ncatalog.v1\"p\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x03\x12\x15\n\rcurrency_code\x18\x05 \x01(\t\x12\x10\n\x08in_stock\x18\x06 \x01(\x08\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\":\n\x12GetProductResponse\x12$\n\x07product\x18\x01 \x01(\x0b\x32\x13.catalog.v1.Product\"\x15\n\x13ListProductsRequest\"=\n\x14ListProductsResponse\x12%\n\x08products\x18\x01 \x03(\x0b\x32\x13.catalog.v1.Product2\xb0\x01\n\x0e\x43\x61talogService\x12K\n\nGetProduct\x12\x1d.catalog.v1.GetProductRequest\x1a\x1e.catalog.v1.GetProductResponse\x12Q\n\x0cListProducts\x12\x1f.catalog.v1.ListProductsRequest\x1a .catalog.v1.ListProductsResponseB3Z1github.com/myshop/api/gen/go/catalog/v1;catalogv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog.v1.catalog_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/myshop/api/gen/go/catalog/v1;catalogv1'
  _globals['_PRODUCT']._serialized_start=48
  _globals['_PRODUCT']._serialized_end=160
  _globals['_GETPRODUCTREQUEST']._serialized_start=162
  _globals['_GETPRODUCTREQUEST']._serialized_end=201
  _globals['_GETPRODUCTRESPONSE']._serialized_start=203
  _globals['_GETPRODUCTRESPONSE']._serialized_end=261
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=263
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=284
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=286
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=347
  _globals['_CATALOGSERVICE']._serialized_start=350
  _globals['_CATALOGSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
