# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order/v1/order_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order/v1/order_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1corder/v1/order_service.proto\x12\x08order.v1\"\x8c\x02\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12&\n\x06status\x18\x03 \x01(\x0e\x32\x16.order.v1.Order.Status\x12\"\n\x05items\x18\x04 \x03(\x0b\x32\x13.order.v1.OrderItem\x12\x14\n\x0ctotal_amount\x18\x05 \x01(\x03\x12\x15\n\rcurrency_code\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\"Y\n\x06Status\x12\x15\n\x11STATUS_UNSECIFIED\x10\x00\x12\x12\n\x0eSTATUS_CREATED\x10\x01\x12\x0f\n\x0bSTATUS_PAID\x10\x02\x12\x13\n\x0fSTATUS_CANCELED\x10\x03\"m\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x03\x12\x15\n\rcurrency_code\x18\x05 \x01(\t\"%\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"5\n\x13\x43reateOrderResponse\x12\x1e\n\x05order\x18\x01 \x01(\x0b\x32\x0f.order.v1.Order2Z\n\x0cOrderService\x12J\n\x0b\x43reateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponseB/Z-github.com/myshop/api/gen/go/order/v1;orderv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order.v1.order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/myshop/api/gen/go/order/v1;orderv1'
  _globals['_ORDER']._serialized_start=43
  _globals['_ORDER']._serialized_end=311
  _globals['_ORDER_STATUS']._serialized_start=222
  _globals['_ORDER_STATUS']._serialized_end=311
  _globals['_ORDERITEM']._serialized_start=313
  _globals['_ORDERITEM']._serialized_end=422
  _globals['_CREATEORDERREQUEST']._serialized_start=424
  _globals['_CREATEORDERREQUEST']._serialized_end=461
  _globals['_CREATEORDERRESPONSE']._serialized_start=463
  _globals['_CREATEORDERRESPONSE']._serialized_end=516
  _globals['_ORDERSERVICE']._serialized_start=518
  _globals['_ORDERSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
