# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification/v1/notification_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification/v1/notification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*notification/v1/notification_service.proto\x12\x0fnotification.v1\"u\n\x17SendNotificationRequest\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.notification.v1.NotificationType\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\"+\n\x18SendNotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*\x89\x01\n\x10NotificationType\x12!\n\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17NOTIFICATION_TYPE_EMAIL\x10\x01\x12\x19\n\x15NOTIFICATION_TYPE_SMS\x10\x02\x12\x1a\n\x16NOTIFICATION_TYPE_PUSH\x10\x03\x32~\n\x13NotificationService\x12g\n\x10SendNotification\x12(.notification.v1.SendNotificationRequest\x1a).notification.v1.SendNotificationResponseB=Z;github.com/myshop/api/gen/go/notification/v1;notificationv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification.v1.notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/myshop/api/gen/go/notification/v1;notificationv1'
  _globals['_NOTIFICATIONTYPE']._serialized_start=228
  _globals['_NOTIFICATIONTYPE']._serialized_end=365
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_start=63
  _globals['_SENDNOTIFICATIONREQUEST']._serialized_end=180
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_start=182
  _globals['_SENDNOTIFICATIONRESPONSE']._serialized_end=225
  _globals['_NOTIFICATIONSERVICE']._serialized_start=367
  _globals['_NOTIFICATIONSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
